#!/usr/bin/env python3
"""
generate-docs.py — build the docs/ tree and mkdocs navigation from skills/.

Consumed by .github/workflows/deploy-skills.yml, which runs this and then `mkdocs build`.
Everything under docs/ is generated: edit skills/, never docs/.

Usage:
  python3 scripts/generate-docs.py
  python3 scripts/generate-docs.py --check     # fail if docs/ or mkdocs.yml is stale
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re
import shutil
import sys

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"
DOCS = ROOT / "docs"

DOMAIN_TITLES = {
    "01-devops-core": "DevOps Core",
    "02-devsecops-and-secops": "DevSecOps & SecOps",
    "03-sre-slo-sla-observability": "SRE & Observability",
    "04-cloud-aws": "AWS",
    "05-cloud-azure": "Azure",
    "06-cloud-gcp": "GCP",
    "07-platform-engineering": "Platform Engineering",
    "08-finops-cloud-economics": "FinOps",
    "productivity": "Productivity",
}


def read(path: Path) -> dict:
    text = path.read_text(encoding="utf-8")
    end = text.find("\n---", 4)
    fm, body = text[4:end], text[end + 4 :]

    def field(k: str) -> str:
        m = re.search(rf"^{k}:\s*(.+)$", fm, re.M)
        return m.group(1).strip() if m else ""

    title_m = re.search(r"^#\s+(.+)$", body, re.M)
    return {
        "name": field("name"),
        "description": field("description"),
        "level": field("level"),
        "tags": [t.strip() for t in field("tags").strip("[]").split(",") if t.strip()],
        "title": title_m.group(1) if title_m else field("name"),
        "domain": path.parent.relative_to(SKILLS).parts[0],
        "body": body,
        "src": path,
    }


def page(s: dict) -> str:
    tags = " ".join(f"`{t}`" for t in s["tags"])
    header = (
        f'!!! info "Skill metadata"\n'
        f"    **Name** `{s['name']}` · **Level** `{s['level']}` · **Tags** {tags}\n\n"
        f"    {s['description']}\n\n"
        f"    Source: [`{s['src'].relative_to(ROOT)}`](https://github.com/mchittineni/"
        f"cloud-platform-skills/blob/main/{s['src'].relative_to(ROOT)})\n"
    )
    # drop the H1 (mkdocs renders the page title) and inject the metadata card
    body = re.sub(r"^#\s+.+$", f"# {s['title']}\n\n{header}", s["body"].lstrip(), count=1, flags=re.M)
    return body.rstrip() + "\n"


def index(skills: list[dict]) -> str:
    out = [
        "# Cloud & Platform Engineering Skills",
        "",
        f"{len(skills)} production-grade skills for Cloud, Platform, SRE, Security and FinOps "
        "engineering — portable across Claude Code, Antigravity/Gemini CLI, Codex, Cursor and "
        "GitHub Copilot.",
        "",
        "Each skill states its own activation triggers and, critically, when to route elsewhere. "
        "Load one skill, never the library.",
        "",
    ]
    for domain, title in DOMAIN_TITLES.items():
        group = [s for s in skills if s["domain"] == domain]
        if not group:
            continue
        out += [f"## {title}", "", "| Skill | Level | Load when |", "| --- | --- | --- |"]
        for s in group:
            parts = s["description"].split("Use when", 1)
            when = ("Use when" + parts[1]).strip() if len(parts) > 1 else s["description"]
            out.append(
                f"| [{s['name']}]({domain}/{s['name']}.md) | {s['level']} | {when.replace('|', '/')} |"
            )
        out.append("")
    out += [
        "## Quality gates",
        "",
        "Every skill passes four gates before merge — structure and mirror sync, offline routing "
        "and content-coverage evals, the 8-point compliance inspection, and generated-target "
        "freshness. See "
        "[CONTRIBUTING.md](https://github.com/mchittineni/cloud-platform-skills/blob/main/CONTRIBUTING.md).",
        "",
    ]
    return "\n".join(out)


def mkdocs_yml(skills: list[dict]) -> str:
    nav = ["nav:", "  - Home: index.md"]
    for domain, title in DOMAIN_TITLES.items():
        group = [s for s in skills if s["domain"] == domain]
        if not group:
            continue
        nav.append(f"  - {title}:")
        for s in group:
            nav.append(f"      - {s['name']}: {domain}/{s['name']}.md")
    return f"""# Generated by scripts/generate-docs.py — do not edit by hand.
site_name: Cloud & Platform Engineering Skills
site_description: >-
  {len(skills)} production-grade, portable engineering skills for DevOps, DevSecOps, SRE,
  AWS, Azure, GCP, Platform Engineering and FinOps.
site_url: https://mchittineni.github.io/cloud-platform-skills/
repo_url: https://github.com/mchittineni/cloud-platform-skills
repo_name: cloud-platform-skills
edit_uri: ""

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle: {{ icon: material/weather-night, name: Switch to dark mode }}
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle: {{ icon: material/weather-sunny, name: Switch to light mode }}
  features:
    - navigation.sections
    - navigation.top
    - navigation.instant
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc: {{ permalink: true }}
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight: {{ anchor_linenums: true }}
  - pymdownx.inlinehilite
  - pymdownx.tabbed: {{ alternate_style: true }}
  - pymdownx.arithmatex: {{ generic: true }}

plugins:
  - search

{chr(10).join(nav)}
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if generated docs are stale")
    args = ap.parse_args()

    skills = sorted((read(p) for p in SKILLS.rglob("SKILL.md")), key=lambda s: (s["domain"], s["name"]))
    if not skills:
        print("error: no skills found", file=sys.stderr)
        return 2

    wanted = {Path("index.md"): index(skills)}
    for s in skills:
        wanted[Path(s["domain"]) / f"{s['name']}.md"] = page(s)

    if args.check:
        stale = [
            str(rel)
            for rel, content in wanted.items()
            if not (DOCS / rel).exists() or (DOCS / rel).read_text(encoding="utf-8") != content
        ]
        cfg = ROOT / "mkdocs.yml"
        if not cfg.exists() or cfg.read_text(encoding="utf-8") != mkdocs_yml(skills):
            stale.append("mkdocs.yml")
        if stale:
            print(f"{len(stale)} generated doc(s) stale — run scripts/generate-docs.py")
            for s in stale[:20]:
                print(f"  - {s}")
            return 1
        print(f"docs/ up to date ({len(skills)} skills)")
        return 0

    if DOCS.exists():
        shutil.rmtree(DOCS)
    for rel, content in wanted.items():
        target = DOCS / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(content, encoding="utf-8")
    (ROOT / "mkdocs.yml").write_text(mkdocs_yml(skills), encoding="utf-8")

    print(f"generated docs/ for {len(skills)} skills across {len({s['domain'] for s in skills})} domains")
    print("next: pip install -r requirements-dev.txt && mkdocs serve")
    return 0


if __name__ == "__main__":
    sys.exit(main())
