#!/usr/bin/env python3
"""
validate-skills.py — quality gates for every SKILL.md in this library.

Enforces the contract that makes a skill usable by *any* agent runtime
(Claude Code, Antigravity/Gemini, Codex, Cursor, Copilot):

  * complete, well-typed frontmatter
  * a `name` that matches its directory (how every runtime addresses a skill)
  * a description that is a routing decision: capability + explicit "Use when" triggers
  * a progressive-disclosure body: one H1, a "When to Use This Skill" routing block,
    and a line budget that keeps the skill cheap to load
  * cross-skill references that actually resolve
  * generated runtime mirrors that are in sync with skills/ (--check-sync)

Usage:
  python3 scripts/validate-skills.py                # gates + warnings
  python3 scripts/validate-skills.py --strict       # warnings are failures
  python3 scripts/validate-skills.py --check-sync   # also verify generated mirrors
  python3 scripts/validate-skills.py --json         # machine-readable report
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"

REQUIRED_FIELDS = ["name", "description", "level", "tags", "compatible_runtimes"]
VALID_LEVELS = ["junior", "mid", "senior", "staff", "principal", "all"]
VALID_RUNTIMES = ["antigravity", "claude", "codex", "copilot", "cursor", "gemini"]

DESC_MIN, DESC_MAX = 120, 700  # hard bounds; Claude truncates ~1024 chars
BODY_WARN_LINES, BODY_FAIL_LINES = 200, 400
TAGS_MIN, TAGS_MAX = 3, 8

TRIGGER_RE = re.compile(r"\buse (when|for|while)\b", re.I)
# A plain YAML scalar containing ": " is a MAPPING, not a string. Frontmatter that a strict parser
# rejects makes the skill unloadable for every runtime that uses a real YAML library — while a
# tolerant hand-rolled parser (like the one below, and like every other gate in this repo) happily
# reads it. That gap is exactly how 36 of 38 skills once shipped with broken frontmatter.
YAML_UNSAFE_PLAIN = re.compile(r":\s|\s#")
YAML_UNSAFE_START = re.compile(r"^[-?:,\[\]{}#&*!|>%@`]")
LEVEL_LEAK_RE = re.compile(r"^\s*(junior|mid|senior|staff|principal)[\w\s/-]*?level\b", re.I)
SECOND_PERSON_RE = re.compile(r"^\s*(you|your|i )\b", re.I)
ROUTING_BLOCK = "## When to Use This Skill"

# Mirrors generated by scripts/sync-all.py: (relative dir, human label)
MIRRORS = [
    (".agents/skills", "Antigravity / .agents"),
    (".claude/skills", "Claude Code / .claude"),
]


def parse_frontmatter(text: str):
    """Minimal, dependency-free YAML frontmatter reader (scalars + inline lists)."""
    if not text.startswith("---\n"):
        return None, "file does not open with '---' YAML frontmatter"
    end = text.find("\n---", 4)
    if end == -1:
        return None, "YAML frontmatter is never closed with '---'"
    raw, body = text[4:end], text[end + 4 :]

    meta: dict[str, object] = {}
    unsafe: list[str] = []
    key = None
    for line in raw.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        if (line.startswith("  ") or line.startswith("\t")) and key:
            meta[key] = f"{meta[key]} {line.strip()}".strip()
            continue
        if ":" not in line:
            continue
        key, val = line.split(":", 1)
        key, val = key.strip(), val.strip()
        if val.startswith("[") and val.endswith("]"):
            meta[key] = [x.strip().strip("'\"") for x in val[1:-1].split(",") if x.strip()]
        elif val in (">-", ">", "|", "|-"):
            meta[key] = ""
        else:
            quoted = len(val) >= 2 and val[0] == val[-1] and val[0] in "\"'"
            if not quoted and (YAML_UNSAFE_PLAIN.search(val) or YAML_UNSAFE_START.match(val)):
                unsafe.append(key)
            meta[key] = val.strip("'\"")
    meta["__yaml_unsafe__"] = unsafe
    return meta, body


FENCE_RE = re.compile(r"^([ \t]*)(```+|~~~+).*$")


def strip_code_fences(body: str) -> str:
    """Blank out fenced code blocks so markdown checks never read code comments."""
    out, fence = [], None
    for line in body.splitlines():
        m = FENCE_RE.match(line)
        if m and fence is None:
            fence = m.group(2)[:3]
            out.append("")
            continue
        if fence is not None:
            if m and m.group(2).startswith(fence):
                fence = None
            out.append("")
            continue
        out.append(line)
    return "\n".join(out)


def validate(path: Path, known_names: set[str]):
    errors: list[str] = []
    warnings: list[str] = []
    text = path.read_text(encoding="utf-8")
    meta, body = parse_frontmatter(text)
    if meta is None:
        return [f"Frontmatter: {body}"], []

    for unsafe_key in meta.pop("__yaml_unsafe__", []):
        errors.append(
            f"frontmatter: '{unsafe_key}' is an unquoted plain scalar containing ': ' or ' #'. "
            "A strict YAML parser reads that as a mapping and fails to load the skill — wrap the "
            "value in double quotes"
        )

    for field in REQUIRED_FIELDS:
        if field not in meta or meta[field] in ("", [], None):
            errors.append(f"frontmatter: missing or empty required field '{field}'")

    # --- name ---------------------------------------------------------------
    name = str(meta.get("name", ""))
    if name:
        if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", name):
            errors.append(f"name: '{name}' must be kebab-case (lowercase, digits, single dashes)")
        if name != path.parent.name:
            errors.append(
                f"name: '{name}' does not match its directory '{path.parent.name}' "
                "(runtimes address skills by directory)"
            )
        if len(name) > 64:
            errors.append(f"name: '{name}' exceeds 64 characters")

    # --- description -------------------------------------------------------
    desc = str(meta.get("description", ""))
    if desc:
        if len(desc) < DESC_MIN:
            errors.append(
                f"description: {len(desc)} chars is too thin (min {DESC_MIN}); "
                "state the capability AND the triggers"
            )
        if len(desc) > DESC_MAX:
            errors.append(f"description: {len(desc)} chars exceeds the {DESC_MAX}-char budget")
        if not TRIGGER_RE.search(desc):
            errors.append(
                "description: no activation trigger — it must contain an explicit "
                "'Use when ...' clause so agents can route to it"
            )
        if LEVEL_LEAK_RE.search(desc):
            errors.append(
                "description: leaks seniority ('Mid-level ...') into the routing text; "
                "seniority belongs in the `level` field"
            )
        if SECOND_PERSON_RE.search(desc):
            errors.append("description: must be written in the third person, not 'You ...'")

    # --- level / tags / runtimes -------------------------------------------
    level = str(meta.get("level", "")).lower()
    if level and level not in VALID_LEVELS:
        errors.append(f"level: '{level}' invalid; allowed: {', '.join(VALID_LEVELS)}")

    tags = meta.get("tags")
    if tags is not None:
        if not isinstance(tags, list):
            errors.append("tags: must be an inline list, e.g. [aws, eks, kubernetes]")
        else:
            if not (TAGS_MIN <= len(tags) <= TAGS_MAX):
                warnings.append(f"tags: {len(tags)} tags; aim for {TAGS_MIN}-{TAGS_MAX}")
            bad = [t for t in tags if not re.fullmatch(r"[a-z0-9]+(-[a-z0-9]+)*", t)]
            if bad:
                errors.append(f"tags: not kebab-case: {', '.join(bad)}")

    runtimes = meta.get("compatible_runtimes")
    if runtimes is not None:
        if not isinstance(runtimes, list):
            errors.append("compatible_runtimes: must be an inline list")
        else:
            bad = [r for r in runtimes if r not in VALID_RUNTIMES]
            if bad:
                errors.append(
                    f"compatible_runtimes: unknown runtime(s) {', '.join(bad)}; "
                    f"allowed: {', '.join(VALID_RUNTIMES)}"
                )

    # --- body --------------------------------------------------------------
    prose = strip_code_fences(body)
    stripped = body.strip()
    if len(stripped) < 400:
        errors.append("body: under 400 characters — not yet an actionable skill")

    h1s = re.findall(r"^#\s+\S.*$", prose, re.M)
    if len(h1s) != 1:
        errors.append(f"body: expected exactly one H1 title, found {len(h1s)}")

    if ROUTING_BLOCK not in prose:
        errors.append(f"body: missing the '{ROUTING_BLOCK}' routing block")
    else:
        block = prose.split(ROUTING_BLOCK, 1)[1].split("\n## ", 1)[0]
        if "Triggers" not in block:
            errors.append(f"body: '{ROUTING_BLOCK}' block has no **Triggers** list")
        if "Route elsewhere" not in block:
            warnings.append(
                f"body: '{ROUTING_BLOCK}' block has no 'Route elsewhere' list — "
                "agents cannot tell when NOT to use this skill"
            )

    line_count = len(text.splitlines())
    if line_count > BODY_FAIL_LINES:
        errors.append(
            f"body: {line_count} lines exceeds the {BODY_FAIL_LINES}-line ceiling; "
            "move depth into references/ (progressive disclosure)"
        )
    elif line_count > BODY_WARN_LINES:
        warnings.append(
            f"body: {line_count} lines is past the {BODY_WARN_LINES}-line comfort budget; "
            "consider references/"
        )

    if not re.search(r"```", body):
        warnings.append("body: no fenced code block — skills should carry runnable artifacts")

    if not re.search(
        r"Anti-Pattern|Best Practices|Golden Rules|Guidelines|Safety Rules|Quality Gates|Checklist|Principles|Standards|Playbook|Selection Guide|Baseline|Matrix|Protocol|Template",
        prose,
        re.I,
    ):
        warnings.append("body: no best-practice / anti-pattern / checklist section found")

    # --- cross-skill references -------------------------------------------
    for ref in set(re.findall(r"`([a-z0-9]+(?:-[a-z0-9]+){2,})`", prose)):
        if ref in known_names or ref == name:
            continue
        if "." in ref or "/" in ref:
            continue
        if re.match(r"^(aws|azure|gcp)-\*$", ref):
            continue
        # only flag things that look like a skill slug we tried to link
        if ref.count("-") >= 2 and ref not in known_names and f"-> `{ref}`" in prose:
            errors.append(f"cross-reference: `{ref}` does not match any skill in this library")

    return errors, warnings


def check_sync(skill_files: list[Path]) -> list[str]:
    problems = []
    expected = {p.parent.name: p.parent for p in skill_files}
    for rel, label in MIRRORS:
        mdir = ROOT / rel
        if not mdir.exists():
            problems.append(f"{label}: '{rel}' does not exist — run scripts/sync-all.py")
            continue
        present = {d.name for d in mdir.iterdir() if d.is_dir()}
        for missing in sorted(set(expected) - present):
            problems.append(f"{label}: missing skill '{missing}' — run scripts/sync-all.py")
        for orphan in sorted(present - set(expected)):
            problems.append(f"{label}: orphaned skill '{orphan}' no longer in skills/")
        for name in sorted(set(expected) & present):
            src, dst = expected[name] / "SKILL.md", mdir / name / "SKILL.md"
            if not dst.exists():
                problems.append(f"{label}: '{name}/SKILL.md' missing")
            elif src.read_text(encoding="utf-8") != dst.read_text(encoding="utf-8"):
                problems.append(f"{label}: '{name}' is stale — run scripts/sync-all.py")
    return problems


# Every surface that carries a routing index. The first four are generated by sync-all.py; README.md
# and STORE.md are authored. A rendering defect is invisible to a byte-comparison gate
# (`sync-all.py --check` proves a file matches what the generator produces, not that the generator
# produced something correct), so the rendered result is inspected directly.
GENERATED_INDEXES = (
    "CLAUDE.md",
    "AGENTS.md",
    ".agents/rules/AGENTS.md",
    ".github/copilot-instructions.md",
    "README.md",
    "STORE.md",
)

# README.md and STORE.md are hand-maintained, so their index can silently drift from skills/ — and
# the README is the repository's front door. These are checked row-by-row against the frontmatter.
AUTHORED_INDEXES = ("README.md",)
ROW_RE = re.compile(r"^\|\s*\[`([a-z0-9-]+)`\]\([^)]+\)\s*\|\s*([a-z]+)\s*\|\s*(.+?)\s*\|\s*$")

# YAML quoting that leaked into rendered prose. Descriptions are double-quoted in source because
# they contain ': '; those quotes are syntax, and a table cell ending in `." |` means the generator
# copied the raw scalar instead of the value.
LEAKED_QUOTE = re.compile(r"""["']\s*\|\s*$""")


def check_generated_indexes() -> list[str]:
    problems = []
    for rel in GENERATED_INDEXES:
        path = ROOT / rel
        if not path.exists():
            problems.append(f"{rel}: missing — run scripts/sync-all.py")
            continue
        text = path.read_text(encoding="utf-8")
        if not text.strip():
            problems.append(f"{rel}: is empty")
            continue
        for lineno, line in enumerate(text.splitlines(), 1):
            if line.startswith("| [`") and LEAKED_QUOTE.search(line):
                problems.append(
                    f"{rel}:{lineno}: index row ends with a stray YAML quote — the generator is "
                    "emitting the raw frontmatter scalar instead of its unquoted value"
                )
    return problems


def load_when(description: str) -> str:
    """The 'Load when' cell for a skill: its trigger clause, rendered exactly as sync-all.py does."""
    parts = description.split("Use when", 1)
    cell = ("Use when" + parts[1]).strip() if len(parts) > 1 else description
    return cell.replace("|", "/")


def check_authored_indexes(skill_files: list[Path]) -> list[str]:
    """Authored index tables must agree with the frontmatter they describe.

    A stale README row misroutes a human the same way a stale description misroutes an agent, and
    nothing else in the pipeline catches it: the README is not generated, so `--check` cannot help.
    """
    problems = []
    expected = {}
    for sf in skill_files:
        meta, _ = parse_frontmatter(sf.read_text(encoding="utf-8"))
        if not meta:
            continue
        name = str(meta.get("name", ""))
        if name:
            expected[name] = (str(meta.get("level", "")), load_when(str(meta.get("description", ""))))
    for rel in AUTHORED_INDEXES:
        path = ROOT / rel
        if not path.exists():
            continue
        seen = set()
        for lineno, line in enumerate(path.read_text(encoding="utf-8").splitlines(), 1):
            m = ROW_RE.match(line)
            if not m:
                continue
            name, level, cell = m.groups()
            if name not in expected:
                problems.append(f"{rel}:{lineno}: index row for '{name}', which is not a skill in skills/")
                continue
            seen.add(name)
            want_level, want_cell = expected[name]
            if level != want_level:
                problems.append(
                    f"{rel}:{lineno}: '{name}' level is '{level}', frontmatter says '{want_level}'"
                )
            if cell != want_cell:
                problems.append(
                    f"{rel}:{lineno}: '{name}' index text has drifted from its description — "
                    "copy the trigger clause verbatim from the frontmatter"
                )
        for missing in sorted(set(expected) - seen):
            problems.append(f"{rel}: no index row for skill '{missing}'")
    return problems


def strict_yaml_crosscheck(skill_files: list[Path]) -> list[str]:
    """Best-effort confirmation with a real YAML parser, when one is installed.

    The stdlib check above is authoritative and always runs; this only adds confidence locally.
    PyYAML is never required — gates in this repository stay stdlib-only.
    """
    try:
        import yaml
    except ImportError:
        return []
    problems = []
    for sf in skill_files:
        text = sf.read_text(encoding="utf-8")
        end = text.find("\n---", 4)
        if not text.startswith("---\n") or end == -1:
            continue
        try:
            loaded = yaml.safe_load(text[4:end])
        except Exception as e:
            problems.append(f"{sf.parent.name}: PyYAML rejects the frontmatter — {str(e).splitlines()[0]}")
            continue
        if not isinstance(loaded, dict):
            problems.append(f"{sf.parent.name}: frontmatter does not parse to a mapping")
    return problems


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--strict", action="store_true", help="treat warnings as failures")
    ap.add_argument("--check-sync", action="store_true", help="also verify generated runtime mirrors")
    ap.add_argument("--json", action="store_true", help="emit a machine-readable report")
    args = ap.parse_args()

    if not SKILLS_DIR.exists():
        print(f"error: {SKILLS_DIR} does not exist", file=sys.stderr)
        return 2

    skill_files = sorted(SKILLS_DIR.rglob("SKILL.md"))
    if not skill_files:
        print(f"error: no SKILL.md found under {SKILLS_DIR}", file=sys.stderr)
        return 2

    known_names = {p.parent.name for p in skill_files}
    report, failed, warned = [], 0, 0

    for sf in skill_files:
        errs, warns = validate(sf, known_names)
        report.append(
            {"skill": sf.parent.name, "path": str(sf.relative_to(ROOT)), "errors": errs, "warnings": warns}
        )
        if errs:
            failed += 1
        if warns:
            warned += 1

    # duplicate names across domains
    dupes = sorted({n for n in known_names if [p.parent.name for p in skill_files].count(n) > 1})
    sync_problems = check_sync(skill_files) if args.check_sync else []
    if args.check_sync:
        sync_problems += check_generated_indexes()
        sync_problems += check_authored_indexes(skill_files)
    yaml_problems = strict_yaml_crosscheck(skill_files)

    if args.json:
        print(
            json.dumps(
                {
                    "skills": report,
                    "duplicate_names": dupes,
                    "sync_problems": sync_problems,
                    "passed": len(skill_files) - failed,
                    "failed": failed,
                    "warned": warned,
                },
                indent=2,
            )
        )
    else:
        print(f"Validating {len(skill_files)} skill(s) in {SKILLS_DIR.relative_to(ROOT)}/\n")
        for r in report:
            if r["errors"]:
                print(f"FAIL  {r['path']}")
                for e in r["errors"]:
                    print(f"      x {e}")
            elif r["warnings"]:
                print(f"WARN  {r['path']}")
            else:
                print(f"PASS  {r['path']}")
            for w in r["warnings"]:
                print(f"      ! {w}")
        if dupes:
            print("\nDuplicate skill names (must be unique across the library):")
            for d in dupes:
                print(f"      x {d}")
        if yaml_problems:
            print("\nStrict YAML cross-check (PyYAML detected):")
            for p in yaml_problems:
                print(f"      x {p}")
        if sync_problems:
            print("\nRuntime mirror sync:")
            for p in sync_problems:
                print(f"      x {p}")
        elif args.check_sync:
            print("\nRuntime mirror sync: all mirrors in sync")
        print(f"\nResult: {len(skill_files) - failed} passed, {failed} failed, {warned} with warnings")

    if failed or dupes or sync_problems or yaml_problems:
        return 1
    if args.strict and warned:
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
